# Generated by Django 5.1.7 on 2026-09-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Helpline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('cyber_crime', 'Cyber Crime'), ('domestic_violence', 'Domestic Violence'), ('mental_health', 'Mental Health'), ('child_helpline', 'Child Helpline'), ('women_safety', 'Women Safety'), ('legal_aid', 'Legal Aid'), ('general', 'General Emergency')], max_length=50)),
                ('country', models.CharField(default='India', max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('languages', models.CharField(blank=True, max_length=200, null=True)),
                ('available_24x7', models.BooleanField(default=True)),
                ('verified_by', models.CharField(blank=True, max_length=200, null=True)),
                ('last_verified_date', models.DateField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField()),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('urgency_tier', models.CharField(blank=True, max_length=50, null=True)),
                ('location_detected', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
