# Generated by Django 5.1.7 on 2026-09-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalResourceCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=100)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('country', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('raw_data', models.JSONField()),
                ('license_type', models.CharField(blank=True, max_length=50, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('ttl_expiry', models.DateTimeField()),
            ],
        ),
    ]
