# Generated by Django 5.1.7 on 2026-09-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_helpline_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helpline',
            options={'ordering': ['-priority', 'name']},
        ),
        migrations.AddIndex(
            model_name='helpline',
            index=models.Index(fields=['category'], name='core_helpli_categor_1a11a8_idx'),
        ),
        migrations.AddIndex(
            model_name='helpline',
            index=models.Index(fields=['country', 'category'], name='core_helpli_country_a59e08_idx'),
        ),
        migrations.AddIndex(
            model_name='helpline',
            index=models.Index(fields=['state', 'district', 'category'], name='core_helpli_state_89293d_idx'),
        ),
        migrations.AddIndex(
            model_name='helpline',
            index=models.Index(fields=['priority'], name='core_helpli_priorit_39a9fe_idx'),
        ),
    ]
