# Generated by Django 5.1.7 on 2026-09-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_helpline_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpline',
            name='country',
            field=models.CharField(db_index=True, default='India', max_length=100),
        ),
        migrations.AlterField(
            model_name='helpline',
            name='state',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
