# Generated by Django 5.1.7 on 2026-09-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_helpline_country_alter_helpline_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='querylog',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
