# Generated by Django 5.1.7 on 2026-09-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_querylog_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpline',
            name='category',
            field=models.CharField(choices=[('cyber_crime', 'Cyber Crime'), ('domestic_violence', 'Domestic Violence'), ('mental_health', 'Mental Health'), ('child_helpline', 'Child Helpline'), ('women_safety', 'Women Safety'), ('legal_aid', 'Legal Aid'), ('health_emergency', 'Health Emergency'), ('general', 'General Emergency')], max_length=50),
        ),
    ]
