# Generated by Django 5.1.7 on 2026-09-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_helpline_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('query_text', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('urgency_tier', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('resources', models.JSONField(default=list)),
                ('reply', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['slug'], name='core_chatse_slug_76dbe3_idx')],
            },
        ),
    ]
