# Generated by Django 5.1.7 on 2026-09-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_chatsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpline',
            name='description',
            field=models.TextField(blank=True, help_text='Extra context for LLM — designation, special instructions, eligibility criteria etc.', null=True),
        ),
    ]
