# Generated by Django 5.1.7 on 2026-09-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_helpline_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpline',
            name='category',
            field=models.CharField(choices=[('cyber_crime', 'Cyber Crime'), ('domestic_violence', 'Domestic Violence'), ('mental_health', 'Mental Health'), ('child_helpline', 'Child Helpline'), ('women_safety', 'Women Safety'), ('legal_aid', 'Legal Aid'), ('health_emergency', 'Health Emergency'), ('animal_husbandry', 'Animal Husbandry'), ('senior_citizen', 'Senior Citizen Support'), ('disaster_relief', 'Disaster Relief'), ('labour_rights', 'Labour Rights'), ('consumer_complaint', 'Consumer Complaint'), ('road_accident', 'Road Accident'), ('missing_person', 'Missing Person'), ('general', 'General Emergency')], max_length=50),
        ),
    ]
