# Generated by Django 5.1.7 on 2026-09-25 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_helpline_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='query_text',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='resources',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='urgency_tier',
        ),
    ]
